# Dockerfile.local
# This file is used to build the frontend image for local development.

FROM node:18

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

# This is needed for hot reloading to work on Windows
ENV WATCHPACK_POLLING true

EXPOSE 3000

CMD ["npm", "run", "dev"]
