version: '3.8'

services:
    backend:
        build:
            context: ./backend
        ports:
            - "4000:4000"
        env_file:
            - ./backend/.env
        networks:
            - moviedb-network

    frontend:
        build:
            context: ./frontend
        ports:
            - "3000:3000"
        env_file:
            - ./frontend/.env
        networks:
            - moviedb-network

networks:
    moviedb-network:
        driver: bridge
